#!/bin/bash
# Schnell-Deployment auf Render.com

echo "🚀 MeinImmoKauf - Render Deployment"
echo "===================================="
echo ""
echo "Dieser Guide zeigt das schnellste Deployment auf Render.com"
echo ""
echo "SCHRITT 1: GitHub Repository"
echo "  1. Gehe zu https://github.com/new"
echo "  2. Repository erstellen: 'meinimmokauf'"
echo "  3. Git-Befehle ausführen:"
echo "     git init"
echo "     git add ."
echo "     git commit -m 'Initial commit'"
echo "     git branch -M main"
echo "     git remote add origin https://github.com/DEIN-USERNAME/meinimmokauf.git"
echo "     git push -u origin main"
echo ""
echo "SCHRITT 2: Render Web Service"
echo "  1. Gehe zu https://render.com/register"
echo "  2. Mit GitHub anmelden"
echo "  3. 'New' > 'Web Service' > GitHub Repository wählen"
echo ""
echo "SCHRITT 3: Konfiguration"
echo "  Name:              meinimmokauf"
echo "  Environment:       Python 3"
echo "  Build Command:     pip install -r requirements.txt"
echo "  Start Command:     streamlit run app.py --server.port=10000 --server.address=0.0.0.0"
echo "  Instance Type:     Free (oder Paid für keine Sleep-Zeiten)"
echo ""
echo "SCHRITT 4: Environment Variables"
echo "  Folgende optional hinzufügen:"
echo "  STREAMLIT_SERVER_HEADLESS=true"
echo "  STREAMLIT_SERVER_PORT=10000"
echo "  STREAMLIT_SERVER_ADDRESS=0.0.0.0"
echo ""
echo "SCHRITT 5: Deploy"
echo "  1. 'Create Web Service' klicken"
echo "  2. Warten (2-5 Minuten)"
echo "  3. URL erhalten: https://meinimmokauf.onrender.com"
echo ""
echo "SCHRITT 6: capacitor.config.ts aktualisieren"
echo "  Öffne: mobile/capacitor.config.ts"
echo "  Ändere: url: 'https://meinimmokauf.onrender.com'"
echo ""
echo "SCHRITT 7: AAB bauen und Play Store"
echo "  cd mobile/android"
echo "  ./gradlew bundleRelease"
echo "  AAB hochladen zu Play Console"
echo ""
echo "✅ Deployment erfolgreich!"
